// import Head from "next/head";
// import Header from "../../components/header"
// import Suggestion from "../../components/suggestion";
// import styles from "../styles/Metaphysics.module.css"
// import React from "react";

// export default function Metaphysics() {
//   const [comments, setComments] = React.useState<boolean>(false);

//   const toggleComments = () => {
//     setComments(!comments);
//   }

//   // if (comments) {
//   //   return (
//   //     <div>comments</div>
//   //   )
//   // }
  
//   return (
//     <>
//       <Head>
//         <title>Logion</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         {/* <link rel="icon" href="/favicon.ico" /> */}
//       </Head>
//       <main className={styles.main}>
//         <Header></Header>
//         <div className={styles.body}>
//           <div className={styles.title}>Metaphysics</div>
//           <div className={styles.paragraphContainer}>
//             <div></div>
//             <div className={styles.paragraph}>
//               <div className={styles.text}>
//                 παντες 
//               </div>
//               <div className={styles.text}>
//                 ανθροποι 
//               </div>
//               <div className={styles.text}>
//                 του
//               </div>
//               <div className={styles.text}>
//                 ειδεναι 
//               </div>
//               <div className={styles.text}>
//                 ορεγονται
//               </div>
//               <div className={styles.text}>
//                 φυσει 
//               </div>
//               <div className={styles.text}>
//                 τῶν 
//               </div>
//               <div className={styles.text}>
//                 σημειον 
//               </div>
//               <div className={styles.text}>
//                 δ' 
//               </div>
//               <div className={styles.text}>
//                 των 
//               </div>
//               <div onClick={toggleComments}>
//                 <Suggestion phrase="αἰσθήσεων"/>
//               </div>
//               <div className={styles.text}>
//                 ἀγάπησις: 
//               </div>
//               <div className={styles.text}>
//                 και
//               </div>
//               <div className={styles.text}>
//                 γαρ 
//               </div>
//               <div className={styles.text}>
//                 της 
//               </div>
//               <div className={styles.text}>
//                 ἀγάπησις: 
//               </div>
//               <div className={styles.text}>
//                 χρειας: 
//               </div>
//               <div className={styles.text}>
//                 αγαπωνται 
//               </div>
//               <div className={styles.text}>
//                 δι' 
//               </div>
//               <div className={styles.text}>
//                 αυτας 
//               </div>
//               <div className={styles.text}>
//                 ....
//               </div>
//             </div>
//             {comments == false ? <div></div> : 
//             <div className={styles.comments}>
//               <div>
//                 <div className={styles.bold}>
//                   GOOD SUGGESTION: 12 Upvotes
//                 </div>
//                 <div className={styles.bold}>
//                   BAD SUGGESTION: 2 Upvotes
//                 </div>
//               </div>
//               <div className={styles.bold}>Comments:</div>
//               <div className={styles.comments}>
//                 <div className={styles.singleComment}><b>Johannes Haubold:</b> I think the first suggestion makes the 
//                   most sense. Common scribal error, and Aristotle tends to use 
//                   this idiom. cf. asdf asdf asdf asdf
//                 </div>
//                 <div className={styles.singleComment}><b>Luigi Batezzato:</b> Great suggestion! Also the structure of 
//                   this sentence seems to suggest this as well.
//                 </div>
//                 <div className={styles.singleComment}><b>SNS Student:</b> Manuscripts L and R seem to agree with this 
//                   assertion. 
//                 </div>
//                 <div className={styles.singleComment}>
//                  <b>2nd SNS Student:</b> R is actually in the same 
//                   family as L.
//                 </div>
//               </div>
//             </div>}
//           </div>
//         </div>
//       </main>
//     </>
//   );
// }
