import Head from "next/head";
import Link from "next/link";
import Header from "../../components/header"
import styles from "../styles/Home.module.css"
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

export default function AnalyzedTexts() {
  return (
    <>
      <Head>
        <title>Logion</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <div style={{"margin": "10px"}}>
            <b>Works:</b>
            <div>
              <Link href="/metaphysics"><u>Aristotle: Metaphysics</u></Link>
              <div>Aristophanes: The Wasps</div>
              <div>Aeschylus: Eumenides</div>
              <div>Homer: The Iliad</div>
            </div>
        </div>
      </main>
    </>
  );
}


export const getServerSideProps = withPageAuthRequired();