import Head from "next/head";
import Header from "../../components/header"
import Link from "next/link";
import styles from "../styles/NewText.module.css"

export default function NewText() {
  return (
    <>
      <Head>
        <title>Logion</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Header></Header>
        <div className={styles.form}>
          {/* <div>
            <div>Is It One of These?</div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Iliad</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Odyssey</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Batrachomyomachia</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Metaphysics</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>The Wasps</label>
            </div>
          </div> */}
          <div>
            <div>What Genre Is It?</div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Epic</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Letters</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Lyric</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Philosophy</label>
            </div>
          </div>
          <div>
            <div>What Meter Is It?</div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Prose</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Dactylic Hexameter</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Sapphic</label>
            </div>
          </div>
          <div>
            <div>Select All Similar Texts</div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Iliad</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Odyssey</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Psellos' Epistles</label>
            </div>
          </div>
          <div>
            <div>Select Your Text Below -- or Select None</div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Iliad</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Odyssey</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Psellos' Epistles</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>Batrachomyomachia</label>
            </div>
            <div>
              <input type="checkbox" className={styles.input}></input>
              <label>None</label>
            </div>
          </div>
          <div className={styles.linkContainer}>
            <div className={styles.links}><Link href="/download-model"><u>Download Model</u></Link></div>
            <div className={styles.links}><Link href="/generate-report"><u>Upload Text and Generate Report</u></Link></div>
          </div>
        </div>
      </main>
    </>
  );
}
